import type { Metadata } from 'next';
import { Fredericka_the_Great, Alumni_Sans_Pinstripe } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const fredericka = Fredericka_the_Great({
    subsets: ['latin'],
    display: 'swap',
    weight: '400',
});

const alumniSans = Alumni_Sans_Pinstripe({
    subsets: ['latin'],
    display: 'swap',
    weight: '400',
});

function Navigation() {
    return (
        <div className="border flex justify-between py-3">
            <div className="border flex flex-row items-center px-3">
                <p className={`${fredericka.className} text-6xl px-5 mb-0`}>VS||JS</p>
                <p className={`${alumniSans.className} text-xl`}>Year 3</p>
            </div>
            <div className="border w-1/3 flex justify-between">
                <div className={`${fredericka.className} border flex flex-auto justify-evenly items-center`}>
                    <Link href={'/'}>Home</Link>
                    <Link href={'/player'}>Music</Link>
                    <Link href={'/player'}>Photos</Link>
                    <Link href={'/player'}>About</Link>
                </div>
                <div className="border flex items-center px-2">
                    <Image src="/images/cat.png" width={50} height={50} alt="logo" />
                </div>
            </div>
        </div>
    );
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navigation />
                {children}
            </body>
        </html>
    );
}
